project_name: bruh
version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    main: ./main.go

brews:
  - repository:
      owner: suntianxun
      name: tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/suntianxun/bruh"
    description: "A beautiful terminal user interface for Homebrew"
